version: "3.8"

services:
    app:
        build: .
        ports:
            - "8000:80"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mysql
        volumes:
            - ./storage:/var/www/html/storage
            - ./public:/var/www/html/public


    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"

volumes:
    mysql_data:
